server:
  port: 80

base:
  mysql: 192.168.33.130

spring:
  #MySql 配置
  datasource:
    url: jdbc:mysql://${base.mysql}/example?serverTimezone=Hongkong&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: Test@123
    driver-class-name: com.mysql.cj.jdbc.Driver